const list = [
    {
        id:1,
        title:"Tee",
        price:80,
        image:"../assets/shirt.png",
        description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas repudiandae, illo repellendus sed ullam dignissimos consequuntur quos quisquam, odio fugiat necessitatibus eius. Architecto nam minima maiores, eos vitae enim perspiciatis.",
        qty:1,
        sizes:["S","M","L","XL","XXL"]
    },
    {
        id:2,
        title:"TeeTwo",
        price:800,
        image:"../assets/shirt2.png",
        description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas repudiandae, illo repellendus sed ullam dignissimos consequuntur quos quisquam, odio fugiat necessitatibus eius. Architecto nam minima maiores, eos vitae enim perspiciatis.",
        qty:1,
        sizes:[
            {
                XL:{
                    qty:20,
                    size:"XL"
                },
                S:{
                    qty:10,
                    size:"S"
                },
                XXL:{
                    qty:30,
                    size:"XXL"
                },
                L:{
                    qty:40,
                    size:"L"
                },
            }
        ]
    },
    {
        id:3,
        title:"TeeThree",
        price:50,
        image:"../assets/shirt3.png",
        description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas repudiandae, illo repellendus sed ullam dignissimos consequuntur quos quisquam, odio fugiat necessitatibus eius. Architecto nam minima maiores, eos vitae enim perspiciatis.",
        qty:1,
        sizes:[
            {
                XL:{
                    qty:20,
                    size:"XL"
                },
                S:{
                    qty:10,
                    size:"S"
                },
                XXL:{
                    qty:30,
                    size:"XXL"
                },
                L:{
                    qty:40,
                    size:"L"
                },
            }
        ]
    },
    {
        id:4,
        title:"TeeFour",
        price:220,
        image:"../assets/shirt4.png",
        description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas repudiandae, illo repellendus sed ullam dignissimos consequuntur quos quisquam, odio fugiat necessitatibus eius. Architecto nam minima maiores, eos vitae enim perspiciatis.",
        qty:1,
        sizes:[
            {
                XL:{
                    qty:20,
                    size:"XL"
                },
                S:{
                    qty:10,
                    size:"S"
                },
                XXL:{
                    qty:30,
                    size:"XXL"
                },
                L:{
                    qty:40,
                    size:"L"
                },
            }
        ]
    },
    {
        id:5,
        title:"TeeFive",
        price:80,
        image:"../assets/shirt5.png",
        description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas repudiandae, illo repellendus sed ullam dignissimos consequuntur quos quisquam, odio fugiat necessitatibus eius. Architecto nam minima maiores, eos vitae enim perspiciatis.",
        qty:1,
        sizes:[
            {
                XL:{
                    qty:20,
                    size:"XL"
                },
                S:{
                    qty:10,
                    size:"S"
                },
                XXL:{
                    qty:30,
                    size:"XXL"
                },
                L:{
                    qty:40,
                    size:"L"
                },
            }
        ]
    },
    {
        id:6,
        title:"TeeSix",
        price:870,
        image:"../assets/shirt6.png",
        description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas repudiandae, illo repellendus sed ullam dignissimos consequuntur quos quisquam, odio fugiat necessitatibus eius. Architecto nam minima maiores, eos vitae enim perspiciatis.",
        qty:1,
        sizes:[
            {
                XL:{
                    qty:20,
                    size:"XL"
                },
                S:{
                    qty:10,
                    size:"S"
                },
                XXL:{
                    qty:30,
                    size:"XXL"
                },
                L:{
                    qty:10,
                    size:"L"
                },
            }
        ]
    },

]

export default list;